services:
  raum-db:
    build: ./container/db/.
    container_name: raum-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      TZ: Europe/Berlin
    volumes:
      - ./container/db/postgres_data:/var/lib/postgresql/data
    labels:
      - "sablier.enable=true"
      - "sablier.group=raum"
    networks:
      - mynet
  raum-api:
    build:
      context: .
      dockerfile: ./container/api/Dockerfile
    container_name: raum-api
    depends_on:
      - raum-db
    restart: unless-stopped
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB: ${DB}
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      INIT_ADMIN_PW: ${INIT_ADMIN_PW}
      INIT_ADMIN_NAME: ${INIT_ADMIN_NAME}
      INIT_PW_SALT: ${INIT_PW_SALT}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - mynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raum.rule=Host(`raum-api.micedric.dpdns.org`)"
      - "traefik.http.routers.raum.entrypoints=websecure"
      - "traefik.http.routers.raum.tls.certresolver=myresolver"
      - "traefik.http.routers.raum.middlewares=raum-sablier"
      - "traefik.http.services.raum.loadbalancer.server.port=8080"
      - "traefik.docker.allownonrunning=true"
      - "sablier.enable=true"
      - "sablier.group=raum"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.group=raum"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.sablierUrl=http://sablier:10000"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.sessionDuration=50m"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.dynamic.displayName=Raum"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.dynamic.theme=ghost"
      - "traefik.http.middlewares.raum-sablier.plugin.sablier.dynamic.refreshFrequency=3s"
networks:
  mynet:
    external: true
